pipeline {
  agent {
    kubernetes {
      label 'kaniko-kubectl'
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    command: ["cat"]
    tty: true
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker

  - name: kubectl
    image: 192.168.0.165:5000/custom-kubectl-client:v1
    command: ["cat"]
    tty: true

  volumes:
  - name: kaniko-secret
    emptyDir: {}
"""
    }
  }

  environment {
    REGISTRY = "192.168.0.165:5000"
    IMAGE_NAME = "192.168.0.165:5000/kaniko-demo:latest"
  }

  stages {

    stage('Build & Push Image') {
      steps {
        container('kaniko') {
          sh '''
            /kaniko/executor \
              --context $(pwd) \
              --dockerfile Dockerfile \
              --destination ${IMAGE_NAME} \
              --insecure
          '''
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        container('kubectl') {
          sh '''
            kubectl version --client
            kubectl apply -f k8s/
          '''
        }
      }
    }
  }
}
