apiVersion: v1
kind: Service
metadata:
  name: kaniko-demo-svc
  namespace: transact
spec:
  type: NodePort
  selector:
    app: kaniko-demo
  ports:
    - port: 80
      targetPort: 6080
      nodePort: 30040
